### ISSUE TITLE
StatusCode is not copied in FromOutcomes method

### ISSUE THREAD

**Issue by lbcsy** [kinetiq/Ether.Outcomes#10]
Any reason it does not copy StatusCode when create a IOutcome by using FromOutcomes method?

**Comment by kinetiq** [comment]
Thanks for the question @lbcsy, I am just seeing this question. Major fail on my part.

It looks like you are correct, StatusCode is not being carried over. I will get a fix together for that today. It is past time for a release.

Be aware that StatusCode is being phased out in 3.0.0 in favor of a more flexible Keys dictionary. However, if you are using it heavily, I could leave it in as syntactic sugar. Let me know.

Keys may not be in the current release, however will it will definitely be in the release I'm working on today. StatusCode will also still be in there too. I think this will be 2.9.5

**Comment by kinetiq** [comment]
The release is out!
