### ISSUE TITLE
Issue deserializing Outcome from .Net

### ISSUE THREAD

**Issue by enriquein** [kinetiq/Ether.Outcomes#4]
I've been using this library to return outcomes to client side code, and on that front it works beautifully. However, when the API is being consumed by a .Net client, I'm running into issues deserializing the result into an `OutcomeResult<T>` instance. Most (all?) deserialization libraries require a public default constructor to be able to construct objects for deserialization. `OutcomeResult<T>` doesn't have any public constructors. I'm wondering if it would be possible to add a public default constructor for this purpose.

**Comment by kinetiq** [comment]
Thanks for reaching out! On the surface I see nothing blocking this. Any interest in submitting a quick pull request? 

Right now I believe the constructors are internal, but that is primarily for the purpose of reducing API surface area I believe, and guiding people towards the static API. I will give that up if it means supporting a use case.

**Comment by enriquein** [comment]
I have no problem submitting a pull request later today. It's a very simple tweak, since all we need to do in order to support deserialization is to add a default constructor. If you want, I could add some xmldoc comments specifying that the constructor is meant to be used by deserializers, and not to instantiate outcomes. What do you think?

**Comment by kinetiq** [comment]
Sounds like a solid contribution! Looking forward to seeing it.

**Comment by enriquein** [comment]
There's another issue. In order for libraries to set the properties of new objects, setters can't be protected. This would mean that all `protected set` properties would have to change to have public set access. This would seem like a break in the way you designed the API. 

Maybe a workaround could be to provide a separate "dumb" class that also implements IOutcome. The difference being that this one would have all properties public and just the default constructor. This is pretty much what I had to do in our project to overcome this limitation.

What do you think?

**Comment by kinetiq** [comment]
That seems like a better workaround than changing the API itself. It is an important use case to support, so yes, let's do it. 

Note to self: We just need to make sure we provide some documentation once it's done, otherwise people might have a hard time discovering how you handled this.

**Comment by enriquein** [comment]
Any preferences as to how to name the class? I'm not very good at naming things 😆

**Comment by kinetiq** [comment]
Hmmm... I'm not aware of a convention for "a class that exists so that you can deserialize a class that has too many readonly properties."

DeserializableOutcome? We can always tweak it later.
