### ISSUE TITLE
"Input string was not in a correct format."

### ISSUE THREAD

**Issue by lbcsy** [kinetiq/Ether.Outcomes#7]
Hi,
I have been using your Outcomes for a while and it helps me a lot until today I have a weird error.
I have a function return IOutcom<int> as following:

```
public IOutcome<int> CreateResource(string type, string json, string id)
{
...
IOutcome<IList<ValidationError>> validation = ValidateResource(rType,json);
			
	if (validation.Failure)
	{
		string message = "Resource is invalid: " + JsonConvert.SerializeObject(validation.Value);
				
		return Outcomes.Failure<int>().WithMessage(message);
	}
			
...
}
```
the "return" line keeps raise an exception "Input string was not in a correct format.", I have tried WithMessage("message"), it had the same error, but WithMessage("1") has no problem. It looks it trying to cast the string in WithMessage to int, why?

**Comment by kinetiq** [comment]
Thanks for using Outcomes Ibscy! 

I took a look at with WithMessage method, and it is very simple, all it does is add the message to a list of messages and return itself so the builder pattern can continue:

 ```
        /// <summary>
        /// Add a string to the end of the outcome's message collection.
        /// </summary>
        /// <param name="message">String to add.</param>
        /// <param name="paramList">Shorthand for String.Format</param>
        /// <returns></returns>
        [StringFormatMethod("message")]
        public SuccessOutcomeBuilder<TValue> WithMessage(string message, params object[] paramList)
        {
            message = string.Format(message, paramList);

            base.Messages.Add(message);
            return this;
        }
```

There's nothing happening with integers or casting here at all - base.Messages is a List<string>. Any chance you are accidentally doing something like this?

`return Outcomes.Failure<int>(message);`

That would actually try to set the value of the Outcome (which is int) to a string, and it would cause an error like the one you're getting. 

Otherwise, please let me know what version of Outcomes and environment you are on, and if possible send me a stack trace and I will dig into it further. Thanks!

**Comment by lbcsy** [comment]
Hi kinetiq,
Thanks for your reply.

I have to added project Outcomes to my project and stepped into WithMessage and found that it was doing string formatting as showed above. The root cause of the problem is that the "message" is in Json format and it contains pairs of "{" and "}" which will be interpreted as formatting place holders for string.Format function which expects proper inputs to match the formatttings, nothing to do with integer directly, really depends what is in the Json string.

So I have to change the code to WithMessage("{0}",message) to make it works, maybe you could come up a better solution.

**Comment by kinetiq** [comment]
I see. Interesting timing on this, literally yesterday I wrote some code where (in the event of an error) some json would end up in an Outcome, which would have caused the same problem eventually. I'm sure I have other similar code out there.

Well, you could escape the curly braces either by doubling them: https://stackoverflow.com/questions/3773857/escape-curly-brace-in-string-format

I don't  like this very much... I am open to ideas. I bet it is possible to compare the params with the contents of the curly braces, and if any don't match up, escape them. It bears some research. 

Of course, that would break anyone who is already escaping their json... Unless you detect double curlies and ignore them.

We could also look at retiring this in the new version in favor of string interpolation.

**Comment by lbcsy** [comment]
What if check the paramList first ? At least it won't cause trouble if my intention is a simple string message.

public SuccessOutcomeBuilder<TValue> WithMessage(string message, params object[] paramList)
       {
           if ( paramList !=null && paramList.Length >0)
           {
                message = string.Format(message, paramList);
           }
           base.Messages.Add(message);
           return this;
       }

**Comment by kinetiq** [comment]
I am inclined to say yes just to get you the bandaid that you need, however it does leave open the even more rare edge case where params are specified and json is also included, ie:

```
return Outcomes.Failure().WithMessage("User {0} had a problem. Json: " + jsonWithCurlyBraces, userName); 
```

This would still fail, and I would prefer a solution that completely removes this problem. Any ideas?

**Comment by lbcsy** [comment]
Based on your implementation of WithMessage, I would say WithMessage is an alias of string.Format, but I wouldn't know this until I encountered this issue. I was just following the sample code and made assumption that it takes only one string as the parameter. I wouldn't use string.Format if I already got the final string. If the develop knows WithMessage is actually an alias of string.Format, he would always use WithMessage("{0}", message) for message no need any further formatting, so my suggesting would be modify the sample code in wiki for the time being.

**Comment by kinetiq** [comment]
Well, we are really close to releasing a major version. I could definitely have a .WithMessage and a .WithMessageFormat... That would give people who upgrade an obvious error message that isn't too hard to resolve, and it would prevent your issue from hitting anyone else.

It would also be easy to implement.

That seems like a reasonable path forward.  What do you think?

**Comment by lbcsy** [comment]
Yes, I think two functions are better.

**Comment by kinetiq** [comment]
Yeah. I will try to get to that in the next week or two. Or, if you feel like tackling it, that would be a great contribution and it wouldn't be too difficult. :) 

Would probably help a lot of people. I have to think there are a ton of outcomes that deal with JSON.

**Comment by lbcsy** [comment]
I have created a pull request. This is my first time use Github "pull request", please let me know if I have done something wrong.
